#constants
DYNATRACE_API_KEY = f'DYNATRACE_API_KEY'
DYNATRACE_CLIENT = f'DYNATRACE_API_KEY'
DYNATRACE_URL = f'DYNATRACE_URL'

DYNATRACE_API_KEY_DATA = f''
DYNATRACE_CLIENT_DATA = f''
DYNATRACE_URL_DATA = f''